# Generated by Django 4.0.3 on 2022-03-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Surname')),
                ('password', models.CharField(max_length=512, verbose_name='Password')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin?')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_user', to='money_managment.user')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Income', max_length=10, verbose_name='Operation type')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('amount', models.BigIntegerField(verbose_name='Amount')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_wallet', to='money_managment.wallet')),
            ],
        ),
    ]
