# Generated by Django 4.0.3 on 2022-03-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_managment', '0002_alter_wallet_user_id_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operations',
            old_name='wallet_id',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='user_id',
            new_name='user',
        ),
    ]
