# Generated by Django 4.0.3 on 2022-03-26 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money_managment', '0003_rename_wallet_id_operations_wallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Income', max_length=10, verbose_name='Operation type')),
                ('amount', models.BigIntegerField(verbose_name='Amount')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Comment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_wallet', to='money_managment.wallet')),
            ],
        ),
        migrations.DeleteModel(
            name='Operations',
        ),
    ]
